version: '1'
services:
  apache:
    # image: php:8-apache
    container_name: apache
    build: .
    depends_on:
      - mysql
    volumes:  
      - "./:/var/www/html"
    ports:
      - 80:80
    networks:
      - myNetwork

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ALLOW_EMPTY_PASSWORDS: 1
      MYSQL_ROOT_PASSWORD: qwerty123
      DB_STRICT: false
    ports:
      - 3306:3306
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - myNetwork

  
networks:
  myNetwork:
    driver: bridge