version: "3.8"
services:
    apache:
        container_name: apache
        build: .
        restart: unless-stopped
        depends_on:
            - database
        volumes:  
            - "./:/var/www/html"
        ports:
            - 80:80
        networks:
            - myNetwork

    database:
        container_name: database
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USERNAME: ${DB_USERNAME}

            MYSQL_ALLOW_EMPTY_PASSWORDS: 1
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

            TZ: ${TIME_ZONE}
            B_STRICT: false

        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - myNetwork
  
    composer:
        container_name: composer
        image: composer:latest
        tty: true 
        command: install
        volumes:  
            - "./:/var/www/html"
volumes:
    db-data: ~
  
networks:
    myNetwork:
        driver: bridge